import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import SwitchComponent from "@/components/SwitchComponent";
import { getItems, getRoom } from "lib/db_handler";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context) {
  try {
    const id = parseInt(context.query.id);

    const room = JSON.parse(JSON.stringify(await getRoom(id)));

    const items = JSON.parse(JSON.stringify(await getItems(id)));

    return {
      props: {
        items: items,
        room: room,
      },
    };
  } catch (e) {
    return console.log(e);
  }
}

export default function Room({ room, items }) {
  return (
    <>
      <Head>
        <title>{room[0].roomName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ textAlign: "center" }}>
          <h2 style={{ marginBottom: 24 }} className={inter.className}>
            {room[0].roomName}
          </h2>
          <div className={styles.grid}>
            {items.map((item) => (
              <SwitchComponent
                key={item.id}
                currentState={item.currentState}
                itemID={item.itemName}
              ></SwitchComponent>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
