import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import SwitchComponent from "@/components/SwitchComponent";
const { PrismaClient } = require("@prisma/client");

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context) {
  const prisma = new PrismaClient();

  const id = parseInt(context.query.id);

  try {
    const item = await prisma.item.findMany({
      where: { room_id: id },
    });

    const room = await prisma.room.findMany({
      where: { id: id },
    });

    return {
      props: {
        room: room,
        item: item,
      },
    };
  } catch (e) {
    console.log(e);
  }
}

export default function Room({ room, item }) {
  return (
    <>
      <Head>
        <title>{room[0].name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ textAlign: "center" }}>
          <h2 style={{ marginBottom: 24 }} className={inter.className}>
            {room[0].name}
          </h2>
          <div className={styles.grid}>
            {item.map((item) => (
              <SwitchComponent
                key={item.id}
                currentState={item.state}
                itemID={item.name}
              ></SwitchComponent>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
